using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace BusinessObjects.Base;

/// <summary>
/// This class make sure that all entities have an Id field of type ObjectId for MongoDB.
/// </summary>
public class MongoEntity
{
    [BsonId]
    [BsonRepresentation(BsonType.ObjectId)]
    // This Id is generated by MongoDB, not by the application
    public ObjectId Id { get; set; }
}
